---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-app
spec:
  selector:
    matchLabels:
      app: http-sidecar
  replicas: 1
  template:
    metadata:
      labels:
        app: http-sidecar
    spec:
      containers:
      - name: http-server
        image: michalsw/webapp
        ports:
        - name: appport
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
      - name: http-sidecar
        image: michalsw/proxy
        ports:
        - name: proxyport
          containerPort: 5050
        env:
        - name: PPORT
          value: "5050"
        - name: APORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: http-app-svc
  labels:
    app: http-app-svc
spec:
  selector:
    app: http-sidecar
  type: LoadBalancer
  ports:
    - name: http
      port: 60000
      targetPort: proxyport
