apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
spec:
  selector:
    matchLabels:
      app: http-server
  replicas: 1
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: <image1>
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
      - name: http-sidecar
        image: <image2>
        ports:
        - containerPort: 5050
        env:
        - name: PPORT
          value: "5050"
        - name: APORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: http-server
  labels:
    app: http-server
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
  selector:
    app: http-server